/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.sun.awt.AWTUtilities;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import modelo.URLX;
import modelo.mIconX;


/**
 *
 * @author sebas
 */
public class vAbout extends javax.swing.JFrame {

    private  final mIconX iOk = new mIconX("\\img\\about\\btn.png".replace("\\","/"),210,160);
    private  final mIconX iFB = new mIconX("\\img\\redes\\1.png".replace("\\","/"),45,45);
    private  final mIconX iTW = new mIconX("\\img\\redes\\2.png".replace("\\","/"),45,45);
    private  final mIconX iC = new mIconX("\\img\\redes\\4.png".replace("\\","/"),45,45);
    private  final mIconX iI = new mIconX("\\img\\redes\\6.png".replace("\\","/"),45,45);
    private  final mIconX iY = new mIconX("\\img\\redes\\5.png".replace("\\","/"),45,45);
    private  final String txtPre = "-- Redes Sociales --";
    private  final String txtT = "www.twiter.com/JosueChuqui";
    private  final String txtY = "www.youtube.com/channel/UCF5qCAn-A9Ypk87nbhPQ96w";
    private  final String txtF = "www.fb.com/JosueChuqui98";
    private  final String txtI = "www.instagram.com/JosueChuqui98";
    private  final String txtC = "Chuqui981026@gmail.com";
    private final URLX url = new URLX();


    public vAbout() {
        
        initComponents();
        //
        setIconImage(new ImageIcon(getClass().getResource("/img/index/Escudo_imperio_inca.png")).getImage());
        setLocationRelativeTo(null);
        AWTUtilities.setWindowOpaque(this, false);
        
        // imgInka.setIcon(inka.Standard());
        imgOk.setIcon(iOk.Standard());
        imgFB.setIcon(iFB.Standard());
        imgTw.setIcon(iTW.Standard());
        imgCorreo.setIcon(iC.Standard());
        imgInst.setIcon(iI.Standard());
        imgYou.setIcon(iY.Standard());
        txtRedes.setText(txtPre);
        
        
//        imgOk.setIcon(iOk.Standard());
//        imgclose.setIcon(iClose.Standard());
//        imgSEPH.setIcon(iS.Standard());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgInst = new javax.swing.JLabel();
        imgYou = new javax.swing.JLabel();
        imgTw = new javax.swing.JLabel();
        imgCorreo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        imgFB = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRedes = new javax.swing.JLabel();
        imgChuqui = new javax.swing.JLabel();
        imgOk = new javax.swing.JLabel();
        imgfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgInst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgInst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/redes/white.jpg"))); // NOI18N
        imgInst.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imgInst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgInstMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imgInstMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imgInstMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                imgInstMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                imgInstMouseReleased(evt);
            }
        });
        getContentPane().add(imgInst, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 50, 50));

        imgYou.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgYou.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/redes/white.jpg"))); // NOI18N
        imgYou.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imgYou.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgYouMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imgYouMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imgYouMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                imgYouMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                imgYouMouseReleased(evt);
            }
        });
        getContentPane().add(imgYou, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 50, 50));

        imgTw.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgTw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/redes/white.jpg"))); // NOI18N
        imgTw.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imgTw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgTwMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imgTwMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imgTwMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                imgTwMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                imgTwMouseReleased(evt);
            }
        });
        getContentPane().add(imgTw, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 50, 50));

        imgCorreo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/redes/white.jpg"))); // NOI18N
        imgCorreo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imgCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgCorreoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imgCorreoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imgCorreoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                imgCorreoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                imgCorreoMouseReleased(evt);
            }
        });
        getContentPane().add(imgCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 50, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Acerca de");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Programador:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        imgFB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgFB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/redes/white.jpg"))); // NOI18N
        imgFB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imgFB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgFBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imgFBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imgFBMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                imgFBMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                imgFBMouseReleased(evt);
            }
        });
        getContentPane().add(imgFB, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 50, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Especialidad:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("MS PGothic", 0, 13)); // NOI18N
        jLabel4.setText("Josue Chuqui");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("MS PGothic", 0, 13)); // NOI18N
        jLabel5.setText("Informática");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Sistemas Operativos:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("MS PGothic", 0, 13)); // NOI18N
        jLabel7.setText("Windows / Linux / Mac OS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        txtRedes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRedes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRedes.setText("-- Redes Sociales --");
        txtRedes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(txtRedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 280, 710, -1));

        imgChuqui.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgChuqui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/about/logo.png"))); // NOI18N
        imgChuqui.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(imgChuqui, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 710, 110));

        imgOk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/about/btn.png"))); // NOI18N
        imgOk.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imgOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgOkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imgOkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imgOkMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                imgOkMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                imgOkMouseReleased(evt);
            }
        });
        getContentPane().add(imgOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 230, 180));

        imgfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/about/background.png"))); // NOI18N
        getContentPane().add(imgfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
    }//GEN-LAST:event_formComponentAdded

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      
        
        
    }//GEN-LAST:event_formWindowOpened

    private void imgOkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgOkMouseEntered
      imgOk.setIcon(iOk.Entered());
    }//GEN-LAST:event_imgOkMouseEntered

    private void imgOkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgOkMouseExited
        imgOk.setIcon(iOk.Exited());
    }//GEN-LAST:event_imgOkMouseExited

    private void imgOkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgOkMousePressed
       imgOk.setIcon(iOk.Pressed());
    }//GEN-LAST:event_imgOkMousePressed

    private void imgOkMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgOkMouseReleased
        imgOk.setIcon(iOk.Released());
    }//GEN-LAST:event_imgOkMouseReleased

    private void imgOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgOkMouseClicked
       dispose();
        
        
        
        
    }//GEN-LAST:event_imgOkMouseClicked

    private void imgFBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgFBMouseEntered
        imgFB.setIcon(iFB.Entered());
        txtRedes.setText(txtF);
    }//GEN-LAST:event_imgFBMouseEntered

    private void imgFBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgFBMouseExited
        imgFB.setIcon(iFB.Exited());
        txtRedes.setText(txtPre);
    }//GEN-LAST:event_imgFBMouseExited

    private void imgFBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgFBMousePressed
        imgFB.setIcon(iFB.Pressed());
    }//GEN-LAST:event_imgFBMousePressed

    private void imgFBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgFBMouseReleased
        imgFB.setIcon(iFB.Released());
    }//GEN-LAST:event_imgFBMouseReleased

    private void imgTwMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgTwMouseEntered
        imgTw.setIcon(iTW.Entered());
        txtRedes.setText(txtT);
    }//GEN-LAST:event_imgTwMouseEntered

    private void imgTwMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgTwMouseExited
        imgTw.setIcon(iTW.Exited());
        txtRedes.setText(txtPre);
    }//GEN-LAST:event_imgTwMouseExited

    private void imgTwMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgTwMousePressed
        imgTw.setIcon(iTW.Pressed());
    }//GEN-LAST:event_imgTwMousePressed

    private void imgTwMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgTwMouseReleased
        imgTw.setIcon(iTW.Released());
    }//GEN-LAST:event_imgTwMouseReleased

    private void imgCorreoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgCorreoMouseEntered
        imgCorreo.setIcon(iC.Entered());
        txtRedes.setText(txtC);
        
    }//GEN-LAST:event_imgCorreoMouseEntered

    private void imgCorreoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgCorreoMouseExited
       imgCorreo.setIcon(iC.Exited());
       txtRedes.setText(txtPre);
    }//GEN-LAST:event_imgCorreoMouseExited

    private void imgCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgCorreoMousePressed
       imgCorreo.setIcon(iC.Pressed());
    }//GEN-LAST:event_imgCorreoMousePressed

    private void imgCorreoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgCorreoMouseReleased
        imgCorreo.setIcon(iC.Released());
    }//GEN-LAST:event_imgCorreoMouseReleased

    private void imgInstMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgInstMouseEntered
        imgInst.setIcon(iI.Entered());
        txtRedes.setText(txtI);
    }//GEN-LAST:event_imgInstMouseEntered

    private void imgInstMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgInstMouseExited
        imgInst.setIcon(iI.Exited());
        txtRedes.setText(txtPre);
    }//GEN-LAST:event_imgInstMouseExited

    private void imgInstMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgInstMousePressed
        imgInst.setIcon(iI.Pressed());
    }//GEN-LAST:event_imgInstMousePressed

    private void imgInstMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgInstMouseReleased
       imgInst.setIcon(iI.Released());
    }//GEN-LAST:event_imgInstMouseReleased

    private void imgYouMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgYouMouseEntered
        imgYou.setIcon(iY.Entered());
        txtRedes.setText(txtY);
    }//GEN-LAST:event_imgYouMouseEntered

    private void imgYouMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgYouMouseExited
        imgYou.setIcon(iY.Exited());
        txtRedes.setText(txtPre);
    }//GEN-LAST:event_imgYouMouseExited

    private void imgYouMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgYouMousePressed
        imgYou.setIcon(iY.Pressed());
    }//GEN-LAST:event_imgYouMousePressed

    private void imgYouMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgYouMouseReleased
        imgYou.setIcon(iY.Released());
    }//GEN-LAST:event_imgYouMouseReleased

    private void imgFBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgFBMouseClicked

        url.goToURL(txtF);

     
    }//GEN-LAST:event_imgFBMouseClicked

    private void imgTwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgTwMouseClicked
        url.goToURL(txtT);
    }//GEN-LAST:event_imgTwMouseClicked

    private void imgInstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgInstMouseClicked
        url.goToURL(txtI);
    }//GEN-LAST:event_imgInstMouseClicked

    private void imgYouMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgYouMouseClicked
        url.goToURL(txtY);
    }//GEN-LAST:event_imgYouMouseClicked

    private void imgCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgCorreoMouseClicked
        url.goToURL("mailto:"+txtC);
    }//GEN-LAST:event_imgCorreoMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgChuqui;
    private javax.swing.JLabel imgCorreo;
    private javax.swing.JLabel imgFB;
    private javax.swing.JLabel imgInst;
    private javax.swing.JLabel imgOk;
    private javax.swing.JLabel imgTw;
    private javax.swing.JLabel imgYou;
    private javax.swing.JLabel imgfondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel txtRedes;
    // End of variables declaration//GEN-END:variables
}
