/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.sun.awt.AWTUtilities;
import javax.swing.ImageIcon;
import modelo.ImagenS;

public class vIndex extends javax.swing.JFrame {

  // private ImagenS inka = new ImagenS("src\\img\\index\\logo.png",545,405); 
    
    public vIndex() {
        
        initComponents();
        //setIconImage(new ImageIcon("src/resources/img/Circulo Blanco.png").getImage());
        //AWTUtilities.setWindowOpaque(this, false);
        
       
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgInka = new javax.swing.JLabel();
        imgJosue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgInka.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/gif/loading.gif"))); // NOI18N
        getContentPane().add(imgInka, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 410));
        getContentPane().add(imgJosue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 550, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
    }//GEN-LAST:event_formComponentAdded

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        
        
    }//GEN-LAST:event_formWindowOpened
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgInka;
    private javax.swing.JLabel imgJosue;
    // End of variables declaration//GEN-END:variables
}
