/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.applet.AudioClip;

public class vMusica extends javax.swing.JInternalFrame {

    /**
     * Creates new form vMusica
     */
     // Audio Cofre Magico
    private final String pathCofre =  "\\sound\\musica\\condor pasa.wav";
    private AudioClip sCofre;
    // Audio Video
    private final String pathGame =  "\\sound\\musica\\Inti Raymi.wav";
    private AudioClip sGame;
    // adudio Musica
    private final String pathMusica = "\\sound\\musica\\valicha.wav"; 
    private AudioClip sMusica;
     
     private boolean playing = false;
    
    public vMusica() {
        initComponents();
        // Audio 
       sCofre = java.applet.Applet.newAudioClip(getClass().getResource(pathCofre.replace("\\", "/")));
        sGame = java.applet.Applet.newAudioClip(getClass().getResource(pathGame.replace("\\", "/")));
        sMusica = java.applet.Applet.newAudioClip(getClass().getResource(pathMusica.replace("\\", "/")));
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mCondor = new javax.swing.JButton();
        mValicha = new javax.swing.JButton();
        MInti = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mCondor.setText("Reproducir");
        mCondor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCondorActionPerformed(evt);
            }
        });
        getContentPane().add(mCondor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 130, 40));

        mValicha.setText("Reproducir");
        mValicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mValichaActionPerformed(evt);
            }
        });
        getContentPane().add(mValicha, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, 130, 40));

        MInti.setText("Reproducir");
        MInti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIntiActionPerformed(evt);
            }
        });
        getContentPane().add(MInti, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, 130, 40));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 90)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Musica");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 770, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imagen.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mCondorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCondorActionPerformed
        System.out.println("audio acction ");
        if (!playing){
            
            new Thread(){
                public void start(){
                   sCofre.play();
                   playing = true;
                   System.out.println("Se reprodució audio");
               }
            }.start();
        } else{
            playing = false;
            sCofre.stop();
        }
        
  
    }//GEN-LAST:event_mCondorActionPerformed

    private void mValichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mValichaActionPerformed
        System.out.println("audio acction ");
        if (!playing){
            
            new Thread(){
                public void start(){
                   sGame.play();
                   playing = true;
                   System.out.println("Se reprodució audio");
               }
            }.start();
        } else{
            playing = false;
            sGame.stop();
        }
    }//GEN-LAST:event_mValichaActionPerformed

    private void MIntiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIntiActionPerformed
      System.out.println("audio acction ");
      if (!playing){
            
            new Thread(){
                public void start(){
                   sMusica.play();
                   playing = true;
                   System.out.println("Se reprodució audio");
               }
            }.start();
        } else{
            playing = false;
            sMusica.stop();
        }
    }//GEN-LAST:event_MIntiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MInti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton mCondor;
    private javax.swing.JButton mValicha;
    // End of variables declaration//GEN-END:variables
}
